abstract: Hepburn Romanization using Japanese passport rules
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Lingua-JA-Hepburn-Passport
no_index: 
  directory: 
    - inc
    - t
version: 0.02
